msm8960: mark unused variables
To fix:
"error: unused parameter 'platform' [-Werror,-Wunused-parameter]
error: unused parameter 'snd_device' [-Werror,-Wunused-parameter]"

Change-Id: I505edd2b53810f9bc4534704c81516b32429870c